# Generated by Django 4.2.5 on 2023-09-21 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='game',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publisher',
            name='user',
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
