# Generated by Django 4.2.5 on 2023-09-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0006_alter_game_category_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='pict',
            field=models.ImageField(upload_to='templates/player_img'),
        ),
    ]
