# Generated by Django 4.2.5 on 2023-09-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0009_alter_player_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='pict',
            field=models.ImageField(blank=True, default='null', null=True, upload_to='static/game_img'),
        ),
    ]
