# Generated by Django 4.2.5 on 2023-10-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0010_alter_game_pict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ManyToManyField(blank=True, to='gestione.game'),
        ),
    ]
