# Generated by Django 4.2.5 on 2023-10-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0013_remove_player_game_player_game'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='game',
            field=models.ManyToManyField(to='gestione.game'),
        ),
    ]
