# Generated by Django 4.2.5 on 2023-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0014_alter_player_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='game',
        ),
        migrations.AddField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(blank=True, to='gestione.game'),
        ),
    ]
