# Generated by Django 4.2.5 on 2023-10-06 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0016_alter_player_games'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('game', 'player')},
        ),
    ]
