# Generated by Django 4.2.5 on 2023-10-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0017_alter_review_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='titolo',
            new_name='title',
        ),
    ]
