# Generated by Django 4.2.5 on 2023-10-16 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0021_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='average_gameplay_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='average_music_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='average_performance_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='average_plot_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='game',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='game',
            name='category',
            field=models.CharField(choices=[('adventure', 'adventure'), ('action', 'action'), ('rpg', 'rpg'), ('platform', 'platform'), ('educational', 'educational'), ('sport', 'sport'), ('strategy', 'strategy'), ('horror', 'horror'), ('lifestyle', 'lifestyle')], max_length=20),
        ),
    ]
