# Generated by Django 4.2.5 on 2023-10-19 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestione', '0022_game_average_gameplay_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='console',
            field=models.CharField(choices=[('switch', 'Switch'), ('ds', 'DS'), ('ps1', 'PS1'), ('ps2', 'PS2'), ('ps3', 'PS3'), ('ps4', 'PS4'), ('ps5', 'PS5'), ('xbox', 'Xbox'), ('xbox_360', 'Xbox 360'), ('xbox_one', 'Xbox One'), ('atari_2600', 'Atari 2600'), ('sega_genesis', 'Sega Genesis'), ('snes', 'Super Nintendo (SNES)'), ('gamecube', 'Nintendo GameCube'), ('dreamcast', 'Sega Dreamcast'), ('neo_geo', 'Neo Geo'), ('game_boy', 'Game Boy')], max_length=20),
        ),
    ]
